version: '3.3'

# Development version

services:
  mh-postgres-dev:
    image: postgres:10.2
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=mediheroes"
    ports:
      - "5432:5432"