version: '3.3'
services:
  app:
    image: paradoxxger/mediheroes-backend:latest
    environment:
      - "SPRING_REDIS_HOST=redis"
      - "MEDIHEROES_BUGSNAG_API_KEY=1fe10f647a3646b90e4dcc201909c5df"
    networks:
      mediheroes:
        aliases:
          - backend
  postgres:
    image: postgres:10.2
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=mediheroes"
    networks:
      mediheroes:
        aliases:
          - postgres
  redis:
    image: redis:4.0.8
    networks:
      mediheroes:
        aliases:
          - redis
  frontend:
    image: paradoxxger/mediheroes-frontend:latest
    ports:
      - 80:80
      - 443:443
    networks:
      mediheroes:
        aliases:
          - frontend
    volumes:
      - "/etc/letsencrypt/live/mediheroes.com/fullchain.pem:/etc/letsencrypt/live/mediheroes.com/fullchain.pem"
      - "/etc/letsencrypt/live/mediheroes.com/privkey.pem:/etc/letsencrypt/live/mediheroes.com/privkey.pem"
networks:
  mediheroes:
