version: '3.3'

# Development version

services:
  mh-postgres-dev:
    image: postgres:10.2
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=mediheroes"
    ports:
      - "5432:5432"
  mh-mongo-dev:
    image: mongo:4.0.0
    ports:
      - "27017:27017"
    command: --enableFreeMonitoring on --serviceExecutor adaptive
