version: '3.3'
services:
  app:
    image: paradoxxger/mediheroes-backend:${VERSION}
    environment:
      - "MEDIHEROES_BUGSNAG_API_KEY=${MEDIHEROES_BUGSNAG_API_KEY}"
    networks:
      mediheroes:
        aliases:
          - backend
  postgres:
    image: paradoxxger/mediheroes-postgres:${VERSION}
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DATABASE}"
    networks:
      mediheroes:
        aliases:
          - postgres
    volumes:
      - data/postgres:/var/lib/postgresql/data
  mongo:
    image: paradoxxger/mediheroes-mongodb:${VERSION}
    command: --enableFreeMonitoring on --serviceExecutor adaptive
    networks:
      mediheroes:
        aliases:
          - mongo
    volumes:
      - data/mongo:/data/db
  frontend:
    image: paradoxxger/mediheroes-frontend:${VERSION}
    ports:
      - 80:80
      - 443:443
    networks:
      mediheroes:
        aliases:
          - frontend
    volumes:
      - "/etc/letsencrypt/live/www.mediheroes.com/fullchain.pem:${SSL_CERT}"
      - "/etc/letsencrypt/live/www.mediheroes.com/privkey.pem:${SSL_KEY}"
networks:
  mediheroes:
volumes:
  - data
