version: '3.3'
services:
  app:
    image: paradoxxger/mediheroes-backend:${VERSION}
    environment:
      - "MEDIHEROES_BUGSNAG_API_KEY=${MEDIHEROES_BUGSNAG_API_KEY}"
      - "RELEASE_DATE=${RELEASE_DATE}"
      - "SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}"
      - "SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}"
      - "SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}"
      - "SPRING_DATA_MONGODB_HOST=${SPRING_DATA_MONGODB_HOST}"
      - "SPRING_DATA_MONGODB_PORT=${SPRING_DATA_MONGODB_PORT}"
      - "SPRING_DATA_MONGODB_DATABASE=${SPRING_DATA_MONGODB_DATABASE}"
    networks:
      mediheroes:
        aliases:
          - backend
  postgres:
    image: paradoxxger/mediheroes-postgres:${VERSION}
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DATABASE}"
    networks:
      mediheroes:
        aliases:
          - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  mongo:
    image: paradoxxger/mediheroes-mongo:${VERSION}
    command: --enableFreeMonitoring on --serviceExecutor adaptive
    networks:
      mediheroes:
        aliases:
          - mongo
    volumes:
      - mongo:/data/db
  frontend:
    image: paradoxxger/mediheroes-frontend:${VERSION}
    ports:
      - 80:80
      - 443:443
    networks:
      mediheroes:
        aliases:
          - frontend
    volumes:
      - "/etc/letsencrypt/live/www.mediheroes.com/fullchain.pem:${SSL_CERT}"
      - "/etc/letsencrypt/live/www.mediheroes.com/privkey.pem:${SSL_KEY}"
networks:
  mediheroes:
volumes:
  postgres:
  mongo:
