version: '3.3'
services:
  app:
    image: paradoxxger/mediheroes-backend:latest
    environment:
      - "SPRING_REDIS_HOST=redis"
    ports:
      - "8080:8080"
    networks:
      mediheroes:
        aliases:
          - backend
  postgres:
    image: postgres:10.2
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=mediheroes"
    networks:
      mediheroes:
        aliases:
          - postgres
  redis:
    image: redis:4.0.8
    networks:
      mediheroes:
        aliases:
          - redis
  frontend:
    image: paradoxxger/mediheroes-frontend:latest
    ports:
      - 80:80
      - 443:443
    networks:
      mediheroes:
        aliases:
          - frontend
networks:
  mediheroes:
